name: 'action-test'
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Tj roll action step
        uses: ./
        id: roll
        with:
          apply-code: ${{ secrets.TEST_APPLY_CODE }}
      - name: Get the result
        run: echo "The result was ${{ steps.roll.outputs.result }}"

